Hola Federico, te pido perdón por tanto silencio, estuve terminando un paper para MPSA, luego salimos de vacaciones.

Vi todos tus correos. El reporte de radio fórmula es más normal, contradice aquella nota del financiero de 2011 que le atribuía al PAN el sponsorhip de Lorenzo (y Marván al PRD). Habría que recordar quiénes participaron en la negociación de la cámara, a ver si nos confirma las alineaciones de sponsors, como lo hacía Molinar en el pasado distante.

Gracias por los gráficos que desenterraste. Todo se ve correcto en ellos. Me parece recordar que los problemas empiezan poco después de este periodo. 

Esta semana retomaré las estimaciones estáticas con periodos discretos, a ver cómo evoluciona la segmentación al incluir los semestres de transición hacia la reforma de 2014.

Han aceptado nuestra propuesta para el McCubbins fest. Es buena noticia, ya sólo consigo avanzar en proyectos con deadlines como éste---así como ocurrió con el paper con Moreno que anexo. La conferencia es 24 y 24 de junio.

Un abrazo,

-e



parte 2

#+OPTIONS: toc:nil

Hola Federico, más info. 

También encontré algunos plots. Este modelo hace updates voto-por-voto (en vez de periodos discretos). El consejo Woldenberg se reconoce fácilmente:

#+ATTR_LATEX: :width 7.5cm
[[../../ifeSharedGE/graphs/woldBonicaSmoothLines.pdf]]

El siguiente plot es Ugalde-Valdés con periodos discretos (el modelo dinámico de siempre). La salida del verde dejó a Baños en el extremo, aparentemente jalando un bloque de todos contra Figueroa:

#+ATTR_LATEX: :width 7.5cm
[[/home/eric/Downloads/Desktop/data/rollcall/ife_cg/ifeSharedGE/graphs/allUAVdynQuarter.pdf]]

Pero al extender observaciones hacia la derecha (con modelo voto-por-voto), lo que parecía una realineación se ve más bien como juego en un tablero diferente. Lorenzo (el amarillo de entrada tardía) arranca al sur, luego pasa con Figueroa al norte y todo se descompone:

#+ATTR_LATEX: :width 7.5cm
[[/home/eric/Downloads/Desktop/data/rollcall/ife_cg/ifeSharedGE/graphs/UgaldeEtAlSmoothMarch21.pdf]]

A diferencia del ruido post-2006, cuando todo volvió a la normalidad, en 2011 algo se rompió. ¿El modelo o fue la política mexicana? 

No recuerdo los detalles, pero probamos de todo para identificar el espacio. Sin éxito. Más tarde intentaré estimaciones estáticas año-por-año, a ver cómo se comportan consejeros. 

-e



