(TeX-add-style-hook "ifedyn05"
 (lambda ()
    (LaTeX-add-bibliographies
     "d:/01/Dropbox/mydocs/magar")
    (LaTeX-add-environments
     "changemargin")
    (LaTeX-add-labels
     "S:model"
     "F:all+div"
     "S:results"
     "F:idealPointMatrices"
     "F:drift"
     "F:minmaxmed"
     "S:explaining"
     "F:allwMedian"
     "F:overlap"
     "F:agendaControl"
     "t:WiAndBtw"
     "F:winsize"
     "T:tests"
     "F:ptyComplaints")
    (TeX-add-symbols
     "T"
     "B")
    (TeX-run-style-hooks
     "rotating"
     "multirow"
     "pgfmath"
     "tikz"
     "color"
     "graphicx"
     "pdftex"
     "setspace"
     "lscape"
     "url"
     "amssymb"
     "amsmath"
     "inputenc"
     "ansinew"
     "fontenc"
     "T1"
     "ae"
     "natbib"
     "longnamesfirst"
     "sort"
     "geometry"
     "letterpaper"
     "latex2e"
     "art12"
     "article"
     "letter"
     "12pt")))

